kind: PersistentVolume
apiVersion: v1
metadata:
  name: openkm-repo-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-efs
  nfs:
    server: 10.0.0.111    
  hostPath:
    path: "/mnt/data/openkm-repo"
