apiVersion: v1
kind: PersistentVolume
metadata:
  name: openkm-scans-nfs-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.10
    path: "/public/Scan-Ablage"