apiVersion: v1
kind: PersistentVolume
metadata:
  name: openkm-scans-nfs-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-efs
  nfs:
    server: 10.0.0.111
    path: "/public/Scan-Ablage"