kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openkm-db-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  #persistentVolumeReclaimPolicy: Retain
  storageClassName: aws-efs
  resources:
    requests:
      storage: 20Gi
